### ISSUE TITLE
...

### ISSUE THREAD

**Issue by 88-yun** [xujizhong/Grab-Ticket#1]
这样的话 可以上很多号了就  到时速度不知道 跟不跟的上

**Comment by xujizhong** [comment]
速度应该跟得上 🤔

**Comment by xujizhong** [comment]
速度应该是够的 毕竟都是前端操作 😄

**Comment by 88-yun** [comment]
nice&nbsp; 但是&nbsp;这个软件多开没问题&nbsp;
嗯嗯&nbsp; 谢谢你制作这个软件&nbsp; &nbsp;淘宝的类似吗


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"xujizhong"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月3日(星期二) 晚上10:20
收件人:&nbsp;"xujizhong/Grab-Ticket"<Grab-Ticket@noreply.github.com&gt;;
抄送:&nbsp;"╭温眸 。"<1851816737@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xujizhong/Grab-Ticket] ... (#1)




速度应该跟得上 🤔

**Comment by 88-yun** [comment]
一好像是需要环境吧 我解压之后没有软件可以用
二是 你这个没有计时器对吧 我这有 JS时间源码&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 三
// ==UserScript==
// @name&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;大麦抢票-确认
// @namespace&nbsp; &nbsp; https://www.jwang0614.top/scripts
// @version&nbsp; &nbsp; &nbsp; 0.7.2
// @description&nbsp; 辅助购买大麦网演唱会门票
// @author&nbsp; &nbsp; &nbsp; &nbsp;Olivia Wang
// @match&nbsp; &nbsp; &nbsp; &nbsp; https://buy.damai.cn/orderConfirm*
// @grant&nbsp; &nbsp; &nbsp; &nbsp; none
// @require&nbsp; &nbsp; &nbsp; http://code.jquery.com/jquery-1.11.1.min.js
// ==/UserScript==




var test_url = "https://buy.damai.cn/orderConfirm?exParams=%7B%22damai%22%3A%221%22%2C%22channel%22%3A%22damai_app%22%2C%22umpChannel%22%3A%2210002%22%2C%22atomSplit%22%3A%221%22%2C%22serviceVersion%22%3A%221.8.5%22%7D&amp;buyParam=600583263497_1_4192587404863&amp;buyNow=true&amp;spm=a2oeg.project.projectinfo.dbuy"
var timer = null;
var current_url = null;




var max_time = 5000;
var current_time = 500;


$(document).ready(function(){
&nbsp; &nbsp; window.current_url = window.location.href;
&nbsp; &nbsp; if($(".error-msg").length &gt; 0) {
&nbsp; &nbsp; &nbsp; &nbsp; window.location.reload();
&nbsp; &nbsp; &nbsp; &nbsp; // console.log("error");
&nbsp; &nbsp; } else {
&nbsp; &nbsp; &nbsp; &nbsp; setTimeout(fill_form, 300);


&nbsp; &nbsp; }


});






function fill_form() {
&nbsp; &nbsp; var input = document.querySelector(".delivery-email-form input");
&nbsp; &nbsp; var email = "";


&nbsp; &nbsp; if (input) {


&nbsp; &nbsp; &nbsp; &nbsp; input.value=email;


&nbsp; &nbsp; }


&nbsp; &nbsp; var buyer_number = parseInt($(".ticket-buyer-title em").text());
&nbsp; &nbsp; console.log(buyer_number);
&nbsp; &nbsp; var buyer_list = $(".buyer-list-item input");
&nbsp; &nbsp; for(var i=0; i < buyer_number; i++) {
&nbsp; &nbsp; &nbsp; &nbsp; console.log(buyer_list[i]);
&nbsp; &nbsp; &nbsp; &nbsp; buyer_list[i].click();
&nbsp; &nbsp; }


&nbsp; &nbsp; $(".submit-wrapper button").click();
&nbsp; &nbsp; setTimeout(check_alert, 500);


}




function check_alert() {
&nbsp; &nbsp; var alerts = $(".next-dialog-alert");
&nbsp; &nbsp; if(alerts.length &gt; 0 || window.current_time &gt;= window.max_time) {
&nbsp; &nbsp; &nbsp; &nbsp; window.location.reload();
&nbsp; &nbsp; } else {
&nbsp; &nbsp; &nbsp; &nbsp; window.current_time = window.current_time + 500;
&nbsp; &nbsp; &nbsp; &nbsp; setTimeout(check_alert, 500);
&nbsp; &nbsp; }
}



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"xujizhong"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月3日(星期二) 晚上10:25
收件人:&nbsp;"xujizhong/Grab-Ticket"<Grab-Ticket@noreply.github.com&gt;;
抄送:&nbsp;"╭温眸 。"<1851816737@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xujizhong/Grab-Ticket] ... (#1)




速度应该是够的 毕竟都是前端操作 😄

**Comment by xujizhong** [comment]
下载之后需要npm install一下
计时器是有的 😄

**Comment by 88-yun** [comment]
你方便直接&nbsp;包装成exe吗？？嘿嘿


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"xujizhong"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月4日(星期三) 上午8:08
收件人:&nbsp;"xujizhong/Grab-Ticket"<Grab-Ticket@noreply.github.com&gt;;
抄送:&nbsp;"╭温眸 。"<1851816737@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xujizhong/Grab-Ticket] ... (#1)




Closed #1.

**Comment by 88-yun** [comment]
win10可以操作吗&nbsp;今天我试了下&nbsp; 好像运行不了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"xujizhong"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月3日(星期二) 晚上10:25
收件人:&nbsp;"xujizhong/Grab-Ticket"<Grab-Ticket@noreply.github.com&gt;;
抄送:&nbsp;"╭温眸 。"<1851816737@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xujizhong/Grab-Ticket] ... (#1)




速度应该是够的 毕竟都是前端操作 😄
